### ISSUE TITLE
[Unity] Bug: upm 包的运行时库配置有误

### ISSUE THREAD

**Issue by Geequlim** [Tencent/puerts#1705]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

2.0.4

### Unity的版本 | Unity Version

2022.3.13

### 发生在哪个平台 | Platform

Android

### 错误信息 | Error Message

- Android 平台有 x86_64 的目录但是没有带上动态库
- Linux 平台的 libpuerts 和 libnode 平台勾选的是 Any Platform 导致构建安卓时冲突

### 问题重现 | Bug reproduce

引入 upm 中的包即可复现

**Comment by chexiongsheng** [comment]
你可以解决了，然后提交一下

**Comment by chexiongsheng** [comment]
linux设置提交下你的meta

**Comment by Geequlim** [comment]
不太熟悉 puerts 的构建发布流程，这是我调整后的 meta 文件内容
libnode.so.93.meta 和 libpuerts.so.meta 只有 guid 不同，内容如下

<details>
  <summary>libpuerts.so.meta</summary>

```yaml
fileFormatVersion: 2
guid: 66c93e7007faf4706aa2646687de5900
PluginImporter:
  externalObjects: {}
  serializedVersion: 2
  iconMap: {}
  executionOrder: {}
  defineConstraints: []
  isPreloaded: 1
  isOverridable: 1
  isExplicitlyReferenced: 0
  validateReferences: 1
  platformData:
  - first:
      : Any
    second:
      enabled: 0
      settings:
        Exclude Android: 1
        Exclude Editor: 0
        Exclude Linux64: 0
        Exclude OSXUniversal: 0
        Exclude WebGL: 1
        Exclude Win: 0
        Exclude Win64: 0
  - first:
      Android: Android
    second:
      enabled: 0
      settings:
        AndroidSharedLibraryType: Executable
        CPU: ARMv7
  - first:
      Any: 
    second:
      enabled: 0
      settings: {}
  - first:
      Editor: Editor
    second:
      enabled: 1
      settings:
        CPU: x86_64
        DefaultValueInitialized: true
        OS: Linux
  - first:
      Standalone: Linux64
    second:
      enabled: 1
      settings:
        CPU: None
  - first:
      Standalone: OSXUniversal
    second:
      enabled: 1
      settings:
        CPU: None
  - first:
      Standalone: Win
    second:
      enabled: 1
      settings:
        CPU: None
  - first:
      Standalone: Win64
    second:
      enabled: 1
      settings:
        CPU: None
  userData: 
  assetBundleName: 
  assetBundleVariant: 
```

</details>
